apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    run: mariadb-service
spec:
  selector:
    app: mariadb-statefulset
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-statefulset
spec:
  selector:
    matchLabels:
      app: mariadb-statefulset
  serviceName: mariadb-service
  template:
    metadata:
      labels:
        app: mariadb-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-pvctemplates
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scrumwala-secret
                key: DB_ROOT_PWSD
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scrumwala-secret
                key: DB_PSWD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_NAME
  volumeClaimTemplates:
  - metadata: 
      name: mariadb-pvctemplates
    spec:
      storageClassName: "local-path"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
