apiVersion: v1
kind: Service
metadata:
  name: scrumwala-service
  labels:
    run: scrumwala-service
spec:
  selector:
    app: scrumwala-pod
  ports:
    - port: 8081
      targetPort: 8081
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrumwala-deployment
  labels:
    app: scrumwala-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrumwala-pod
  template:
    metadata:
      labels:
        app: scrumwala-pod
    spec:
      initContainers:
      - name: scrumwala-init-migrate
        image: hussaingandhi/scrumwala:3.0
        ports:
        - containerPort: 8081
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_HOST
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_NAME
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scrumwala-secret
                key: DB_PSWD
        command: ["/bin/sh", "-c"]
        args: ["php artisan migrate --force"]
      containers:
      - name: scrumwala
        image: hussaingandhi/scrumwala:3.0
        ports:
        - containerPort: 8081
        env:
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: scrumwala-secret
                key: APP_KEY
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_HOST
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_NAME
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: scrumwala-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scrumwala-secret
                key: DB_PSWD
        command: ["/bin/sh", "-c"]
        args: ["php artisan serve --host 0.0.0.0 --port 8081"]
        # args: ["php composer.phar update --no-scripts --no-interaction && php composer.phar install --no-scripts --no-interaction && php artisan migrate --force && php artisan serve --host 0.0.0.0 --port 8081"]